pub mod ast;
pub mod constant;
pub mod declare;
pub mod func;
pub mod id;
pub mod ty;
use arora_module_core::{ImportAsset, ModuleAsset, Reader, Writer};
use arora_registry::{ModuleFrozen, TypeDefinitionFrozen};
use arora_vfs::{Directory, Entry, File};
use ast::{
    Block, Declaration, Expression, Extern, FunctionImplementation, FunctionPrototype,
    IncludeStyle, Namespace, NewLine, PreprocessorDirective, Statement, TranslationUnit, TypeRef,
    Variable,
};
use ast::{ToExpression, ToPrettyString};
use clap::Parser;
use convert_case::{Case, Casing};
use semio_record::module::v0::frozen::{ExportKind, Parameter};
use semver::Version;
use std::path::PathBuf;
use std::{
    collections::{hash_map, HashMap, HashSet},
    str::FromStr,
};
use tokio::io::{stdin, stdout, AsyncWriteExt};
use ty::OPTIONAL_TYPENAME;
use uuid::Uuid;

pub const AUTOGENERATED_WARNING: &str =
    "// This file was autogenerated by arora-module-cli. Do not edit.\n";

#[derive(Debug)]
pub enum NameStyle {
    UpperCamelCase,
    LowerCamelCase,
    SnakeCase,
}

impl NameStyle {
    pub fn convert(&self, name: &str) -> String {
        let name = name.replace(['-', '_'], " ");
        match self {
            Self::UpperCamelCase => name.to_case(Case::UpperCamel),
            Self::LowerCamelCase => name.to_case(Case::Camel),
            Self::SnakeCase => name.to_case(Case::Snake),
        }
    }
}

impl FromStr for NameStyle {
    type Err = anyhow::Error;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s {
            "upper_camel" => Ok(Self::UpperCamelCase),
            "camel" => Ok(Self::LowerCamelCase),
            "snake" => Ok(Self::SnakeCase),
            _ => Err(anyhow::anyhow!("Invalid method name style: {}", s)),
        }
    }
}

#[derive(Parser, Debug)]
#[clap(long_about = None)]
pub struct Args {
    #[clap(long, name = "self-id")]
    pub self_id: String,

    #[clap(long, name = "self-version")]
    pub self_version: String,
}

pub struct Context<'a> {
    pub args: &'a Args,
    pub types: HashMap<Uuid, TypeDefinitionFrozen>,
    pub grouped_import_symbols: HashMap<Uuid, Vec<ImportAsset>>,
    pub module_id: Uuid,
    pub module_version: Version,
    pub module: Option<ModuleFrozen>,
}

fn generate_type<'a>(context: &Context<'a>, id: &Uuid) -> anyhow::Result<Directory> {
    let ty = context
        .types
        .get(id)
        .ok_or_else(|| anyhow::anyhow!("Type not found: {}", id))?;

    let mut source = Directory::new();
    let mut source_types = Directory::new();

    let mut source_declarations = Vec::new();
    source_declarations.extend_from_slice(&[
        Declaration::include_local(format!("types/{}.hpp", ty.name())),
        Declaration::new_line(1),
    ]);

    source_declarations.extend_from_slice(&declare::type_constants_impl(id, ty));
    source_declarations.extend_from_slice(&declare::ty_impl(context, id, ty));

    let source_content = TranslationUnit {
        declarations: source_declarations,
    }
    .to_pretty_string(0);

    source_types.insert(format!("{}.cpp", ty.name()), File::new(source_content))?;

    source.insert("types", source_types)?;

    let mut include = Directory::new();
    let mut include_types = Directory::new();

    let guard_name = include_guard_name(&format!("TYPES_{}", ty.name()));

    let mut include_declarations = vec![
        Declaration::ifndef(&guard_name),
        Declaration::define(&guard_name),
        Declaration::new_line(1),
        Extern {
            name: "C".to_string(),
            block: Block {
                statements: vec![
                    Declaration::include_system("arora/buffers.h"),
                    Declaration::include_system("arora/util.h"),
                ],
                ..Default::default()
            },
        }
        .into(),
        Declaration::new_line(1),
        Declaration::include_system("arora/buffer/deserialize.hpp"),
        Declaration::include_system("arora/buffer/serialize.hpp"),
        Declaration::new_line(1),
        Declaration::include_system("cmath"),
        Declaration::include_system("cstdint"),
        Declaration::include_system("optional"),
        Declaration::new_line(1),
    ];

    ty.direct_dependencies().iter().for_each(|dep| {
        let dep_header = context
            .types
            .get(dep)
            .unwrap_or_else(|| panic!("unknown type {}", dep));
        include_declarations.push(
            PreprocessorDirective::Include(
                format!("types/{}.hpp", dep_header.name()),
                IncludeStyle::Local,
            )
            .into(),
        );
    });
    include_declarations.extend_from_slice(&declare::type_constants(id, ty));
    include_declarations.extend([
        declare::ty(context, ty).into(),
        Declaration::new_line(1),
        declare::type_of(ty).into(),
        Declaration::new_line(1),
        declare::deserializer(context, id, ty).into(),
        Declaration::new_line(1),
        declare::serializer(context, id, ty).into(),
        Declaration::new_line(1),
        Declaration::endif(),
    ]);

    let include_content = TranslationUnit {
        declarations: include_declarations,
    }
    .to_pretty_string(0);

    include_types.insert(format!("{}.hpp", ty.name()), File::new(include_content))?;

    include.insert("types", include_types)?;

    let mut root = Directory::new();
    root.insert("source", source)?;
    root.insert("include", include)?;

    // Write out a C++ header
    Ok(root)
}

fn generate_module_imports<'a>(
    context: &Context<'a>,
    imports: &Vec<ImportAsset>,
) -> anyhow::Result<Directory> {
    let module_id = imports.first().unwrap().module_id.to_owned();
    let module_name = imports.first().unwrap().module_name.to_owned();
    let id_name = identifier_name(&module_name);

    let mut source = Directory::new();

    let mut source_declarations = Vec::new();

    source_declarations.push(Declaration::include_local(format!("{}.hpp", module_name)));
    source_declarations.push(Declaration::include_system("arora/arora.hpp"));
    source_declarations
        .push(PreprocessorDirective::Include("cassert".to_string(), IncludeStyle::System).into());
    source_declarations.push(
        Extern {
            name: "C".to_string(),
            block: Block {
                statements: vec![
                    PreprocessorDirective::Include(
                        "arora/buffers.h".to_string(),
                        IncludeStyle::System,
                    )
                    .into(),
                    PreprocessorDirective::Include("arora/util.h".to_string(), IncludeStyle::System)
                        .into(),
                ],
                ..Default::default()
            },
        }
        .into(),
    );
    source_declarations.push(
        PreprocessorDirective::Include(
            "arora/buffer/deserialize.hpp".to_string(),
            IncludeStyle::System,
        )
        .into(),
    );
    source_declarations.push(
        PreprocessorDirective::Include("arora/buffer/serialize.hpp".to_string(), IncludeStyle::System)
            .into(),
    );
    source_declarations.push(Declaration::new_line(1));
    source_declarations
        .push(declare::uuid_variable(id::module_uuid(&module_name), &module_id).into());

    // Create UUID variables (used in function implementations)
    for import_asset in imports {
        match &import_asset.import.kind {
            ExportKind::Function(func) => {
                source_declarations.push(
                    declare::uuid_variable(
                        id::function_uuid(&import_asset.import.name),
                        &import_asset.id,
                    )
                    .into(),
                );
                for (parameter_id, parameter) in func.parameters.iter() {
                    source_declarations.push(
                        declare::uuid_variable(
                            id::parameter_uuid(&import_asset.import.name, &parameter.name),
                            parameter_id,
                        )
                        .into(),
                    );
                }
            }
        }
        source_declarations.push(Declaration::new_line(1));
    }

    let mut extern_declarations = Vec::new();

    // Write out the actual function implementations
    for import_asset in imports {
        match &import_asset.import.kind {
            ExportKind::Function(func) => {
                let mut parameters = Vec::new();

                for parameter_id in func.parameter_ordering.iter() {
                    let parameter = func.parameters.get(parameter_id).ok_or(anyhow::anyhow!(
                        "parameter ordering does not match parameters {}",
                        parameter_id
                    ))?;
                    parameters.push(ast::Parameter {
                        name: parameter.name.to_owned(),
                        type_ref: ast::TypeRef {
                            ty: ty::type_name(context, &parameter.ty),
                            constant: !parameter.mutable,
                            reference: true,
                            ..Default::default()
                        },
                    });
                }

                let mut function_declarations = vec![
                    declare::arora_buffer_writer().into(),
                    declare::arora_buffer_writer_begin_structure(
                        &id::function_uuid(&import_asset.import.name),
                        (func.parameters.len() as u32).to_expression(),
                    )
                    .into(),
                ];

                for parameter_id in &func.parameter_ordering {
                    let parameter = func.parameters.get(parameter_id).ok_or(anyhow::anyhow!(
                        "parameter ordering does not match parameters {}",
                        parameter_id
                    ))?;
                    function_declarations.push(
                        declare::arora_buffer_writer_add_structure_field(
                            id::parameter_uuid(&import_asset.import.name, &parameter.name)
                                .to_expression(),
                        )
                        .into(),
                    );
                    function_declarations.push(
                        format!(
                            "arora::buffer::serialize<{}>",
                            ty::type_name(context, &parameter.ty)
                        )
                        .to_expression()
                        .call(["writer".to_expression(), parameter.name.to_expression()])
                        .into_statement()
                        .into(),
                    );
                }

                function_declarations.extend_from_slice(&[
                    // const std::uint8_t *__arora_arg__ = arora_buffer_writer_finalize(writer);
                    Variable {
                        name: "__arora_arg__".to_string(),
                        ty: ty::U8_CONST_PTR.clone(),
                        value: Some(declare::arora_buffer_writer_finalize()),
                        ..Default::default()
                    }
                    .into(),
                    // std::uint8_t  *__arora_result__ = arora_dispatch(MODULE_UUID, FUNCTION_UUID, __arora_arg__);
                    Variable {
                        name: "__arora_result__".to_string(),
                        ty: ty::U8_PTR.clone(),
                        value: Some(func::ARORA_DISPATCH.call([
                            id::module_uuid(&module_name).to_expression(),
                            id::function_uuid(&import_asset.import.name).to_expression(),
                            "__arora_arg__".to_expression(),
                        ])),
                        ..Default::default()
                    }
                    .into(),
                    // assert(__arora_result__ != NULL);
                    func::ASSERT
                        .call(["__arora_result__"
                            .to_expression()
                            .not_equal("0".to_expression())])
                        .into_statement()
                        .into(),
                    // arora_buffer_reader *reader = arora_buffer_reader_new();
                    Variable {
                        name: "reader".to_string(),
                        ty: ty::ARORA_BUFFER_READER_PTR.clone(),
                        value: Some(declare::arora_buffer_reader_new(
                            "__arora_result__".to_expression(),
                        )),
                        ..Default::default()
                    }
                    .into(),
                    // const std::uint8_t __arora_result_type__ = arora_buffer_reader_next_type(reader);
                    Variable {
                        name: "__arora_result_type__".to_string(),
                        ty: ty::U8.clone(),
                        value: Some(declare::arora_buffer_reader_next_type()),
                        ..Default::default()
                    }
                    .into(),
                    // assert(__arora_result_type__ == ARORA_BUFFER_TYPE_STRUCTURE);
                    func::ASSERT
                        .call(["__arora_result_type__"
                            .to_expression()
                            .equal(constant::ARORA_BUFFER_TYPE_STRUCTURE.clone())])
                        .into_statement()
                        .into(),
                    // arora_get_structure_result structure_metadata = arora_buffer_reader_get_structure(reader);
                    Variable {
                        name: "structure_metadata".to_string(),
                        ty: ty::ARORA_GET_STRUCTURE_RESULT.clone(),
                        value: Some(declare::arora_buffer_reader_get_structure()),
                        ..Default::default()
                    }
                    .into(),
                    // assert(arora_uuid_compare(structure_metadata.id, FUNCTION_UUID) == 0);
                    func::ASSERT
                        .call([func::ARORA_UUID_COMPARE
                            .call([
                                "structure_metadata".to_expression().dot("id"),
                                id::function_uuid(&import_asset.import.name).to_expression(),
                            ])
                            .equal("0".to_expression())])
                        .into_statement()
                        .into(),
                    // assert(structure_metadata.field_count > 0);
                    func::ASSERT
                        .call(["structure_metadata"
                            .to_expression()
                            .dot("field_count")
                            .to_expression()
                            .greater_than("0".to_expression())])
                        .into_statement()
                        .into(),
                    // const std::uint8_t *field_id = arora_buffer_reader_get_structure_field(reader);
                    Variable {
                        name: "field_id".to_string(),
                        ty: ty::U8_CONST_PTR.clone(),
                        value: Some(declare::arora_buffer_reader_get_structure_field()),
                        ..Default::default()
                    }
                    .into(),
                    // assert(arora_uuid_compare(field_id, FUNCTION_UUID) == 0);
                    func::ASSERT
                        .call([func::ARORA_UUID_COMPARE
                            .call([
                                "field_id".to_expression(),
                                id::function_uuid(&import_asset.import.name).to_expression(),
                            ])
                            .equal("0".to_expression())])
                        .into_statement()
                        .into(),
                    // const std::optional<RETURN_TYPE> __arora_return__ = arora::buffer::deserialize<RETURN_TYPE>(reader);
                    Variable {
                        name: "__arora_return__".to_string(),
                        ty: ty::optional_const(&TypeRef {
                            ty: ty::type_name(context, &func.return_ty),
                            constant: false,
                            ..Default::default()
                        }),
                        value: Some(
                            format!(
                                "arora::buffer::deserialize<{}>",
                                ty::type_name(context, &func.return_ty)
                            )
                            .to_expression()
                            .call(["reader".to_expression()]),
                        ),
                        ..Default::default()
                    }
                    .into(),
                    // arora_buffer_reader_free(reader);
                    func::ARORA_BUFFER_READER_FREE
                        .call(["reader".to_expression()])
                        .into_statement()
                        .into(),
                    // free(__arora_result__);
                    func::FREE
                        .call(["__arora_result__".to_expression()])
                        .into_statement()
                        .into(),
                    // return __arora_result__;
                    Statement::Return("__arora_return__".to_expression()).into(),
                ]);

                extern_declarations.push(
                    FunctionImplementation {
                        name: format!(
                            "{}::{}",
                            id_name,
                            identifier_name(&import_asset.import.name)
                        ),
                        parameters,
                        ret: Some(ty::optional(&TypeRef {
                            ty: ty::type_name(context, &func.return_ty),
                            ..Default::default()
                        })),
                        body: Block {
                            statements: function_declarations,
                            semicolon: false,
                        },
                        ..Default::default()
                    }
                    .into(),
                );
            }
        }
    }

    source_declarations.extend_from_slice(&extern_declarations);

    let source_content = TranslationUnit {
        declarations: source_declarations,
    }
    .to_pretty_string(0);

    source.insert(
        format!("{}.cpp", module_name.to_owned()),
        File::new(source_content),
    )?;

    let mut include = Directory::new();

    let include_guard = include_guard_name(&module_name);

    let mut include_declarations = vec![
        Declaration::ifndef(&include_guard),
        Declaration::define(&include_guard),
        Declaration::new_line(1),
        Declaration::include_system("cmath"),
        Declaration::include_system("cstdint"),
        Declaration::include_system("optional"),
        Declaration::new_line(1),
    ];

    for import in imports {
        let mut deps = HashSet::new();
        import.import.dependencies(&mut deps);
        for ty in deps {
            let dep_header = context.types.get(&ty.id).unwrap();
            include_declarations.push(
                PreprocessorDirective::Include(
                    format!("types/{}.hpp", dep_header.name()),
                    IncludeStyle::Local,
                )
                .into(),
            );
        }
    }

    let mut namespace_declarations = vec![];

    for import in imports {
        match &import.import.kind {
            ExportKind::Function(func) => {
                let mut parameters = Vec::new();
                for parameter_id in func.parameter_ordering.iter() {
                    let parameter = func.parameters.get(parameter_id).unwrap();
                    parameters.push(ast::Parameter {
                        type_ref: ast::TypeRef {
                            ty: ty::type_name(context, &parameter.ty),
                            constant: !parameter.mutable,
                            reference: true,
                            ..Default::default()
                        },
                        name: parameter.name.clone(),
                    });
                }

                namespace_declarations.push(
                    FunctionPrototype {
                        name: import.import.name.to_string(),
                        parameters,
                        ret: Some(ty::optional(&TypeRef {
                            ty: ty::type_name(context, &func.return_ty),
                            ..Default::default()
                        })),
                        ..Default::default()
                    }
                    .into(),
                );
            }
        }
    }

    include_declarations.push(
        Namespace {
            name: id_name.clone(),
            declarations: namespace_declarations,
        }
        .into(),
    );

    include_declarations.extend_from_slice(&[Declaration::new_line(1), Declaration::endif()]);

    let include_content = TranslationUnit {
        declarations: include_declarations,
    }
    .to_pretty_string(0);

    include.insert(format!("{}.hpp", module_name), File::new(include_content))?;

    let mut root = Directory::new();
    root.insert("source", source)?;
    root.insert("include", include)?;

    // Write out a C++ header
    Ok(root)
}

fn include_guard_name(name: &str) -> String {
    format!("_{}_HPP_", name.replace('-', "_").to_uppercase())
}

fn identifier_name(name: &str) -> String {
    name.replace('-', "_")
}

fn identifier_uuid(uuid: &Uuid) -> String {
    uuid.to_string().replace("-", "_")
}

fn optional(type_ref: TypeRef, mutable: bool, reference: bool) -> TypeRef {
    TypeRef {
        ty: OPTIONAL_TYPENAME.to_string(),
        arguments: Some(vec![type_ref]),
        constant: !mutable,
        reference,
        ..Default::default()
    }
}

fn generate_self_header<'a>(context: &Context<'a>) -> anyhow::Result<TranslationUnit> {
    let module = &context.module.as_ref().unwrap();
    let guard_name = include_guard_name(&module.name);
    let id_name = identifier_name(&module.name);

    let mut declarations: Vec<Declaration> = vec![
        PreprocessorDirective::Ifndef(guard_name.clone()).into(),
        PreprocessorDirective::Define(guard_name).into(),
        NewLine { count: 1 }.into(),
        PreprocessorDirective::Include("cstdint".to_string(), IncludeStyle::System).into(),
        PreprocessorDirective::Include("optional".to_string(), IncludeStyle::System).into(),
        PreprocessorDirective::Include("string".to_string(), IncludeStyle::System).into(),
        PreprocessorDirective::Include("vector".to_string(), IncludeStyle::System).into(),
    ];

    for export in context.module.as_ref().unwrap().exports.values() {
        let mut dependencies = HashSet::new();
        export.dependencies(&mut dependencies);
        dependencies.into_iter().for_each(|dep| {
            let dep_header = context.types.get(&dep.id).unwrap();
            declarations.push(
                PreprocessorDirective::Include(
                    format!("types/{}.hpp", dep_header.name()),
                    IncludeStyle::Local,
                )
                .into(),
            );
        });
    }

    declarations.push(NewLine { count: 1 }.into());

    let mut namespace_declarations: Vec<Declaration> = Vec::new();

    for export in context.module.as_ref().unwrap().exports.values() {
        let name = identifier_name(&export.name);
        match &export.kind {
            ExportKind::Function(f) => {
                let mut parameters = Vec::new();
                for parameter_id in f.parameter_ordering.iter() {
                    let parameter = f.parameter(parameter_id).unwrap();
                    parameters.push(ast::Parameter {
                        name: parameter.name.clone(),
                        type_ref: optional(
                            TypeRef {
                                ty: ty::type_name(context, &parameter.ty).to_string(),
                                ..Default::default()
                            },
                            parameter.mutable,
                            true,
                        ),
                    });
                }

                namespace_declarations.push(
                    FunctionPrototype {
                        name,
                        ret: Some(TypeRef {
                            ty: ty::type_name(context, &f.return_ty).to_string(),
                            ..Default::default()
                        }),
                        parameters,
                        ..Default::default()
                    }
                    .into(),
                );
            }
        }
    }

    declarations.push(
        Namespace {
            name: id_name.clone(),
            declarations: namespace_declarations,
        }
        .into(),
    );

    declarations.push(NewLine { count: 1 }.into());
    declarations.push(PreprocessorDirective::Endif.into());

    Ok(TranslationUnit { declarations })
}

fn parameter_variable_name(parameter_id: &Uuid, parameter: &Parameter) -> String {
    format!(
        "{}_{}",
        identifier_name(parameter.name.as_str()),
        identifier_uuid(parameter_id)
    )
}

fn generate_self_source<'a>(context: &Context<'a>) -> anyhow::Result<TranslationUnit> {
    let module_id = &context.module_id;
    let module = &context.module.as_ref().unwrap();

    let mut declarations = Vec::new();
    declarations.push(
        PreprocessorDirective::Include(format!("{}.hpp", module.name), IncludeStyle::Local).into(),
    );
    declarations
        .push(PreprocessorDirective::Include("cassert".to_string(), IncludeStyle::System).into());
    declarations.push(
        Extern {
            name: "C".to_string(),
            block: Block {
                statements: vec![
                    PreprocessorDirective::Include(
                        "arora/buffers.h".to_string(),
                        IncludeStyle::System,
                    )
                    .into(),
                    PreprocessorDirective::Include(
                        "arora/util.h".to_string(),
                        IncludeStyle::System,
                    )
                    .into(),
                ],
                ..Default::default()
            },
        }
        .into(),
    );
    declarations.push(
        PreprocessorDirective::Include(
            "arora/buffer/deserialize.hpp".to_string(),
            IncludeStyle::System,
        )
        .into(),
    );
    declarations.push(
        PreprocessorDirective::Include(
            "arora/buffer/serialize.hpp".to_string(),
            IncludeStyle::System,
        )
        .into(),
    );

    declarations.push(NewLine { count: 1 }.into());

    declarations.push(declare::uuid_variable(id::module_uuid(&module.name), module_id).into());

    for (export_id, export) in &context.module.as_ref().unwrap().exports {
        match &export.kind {
            ExportKind::Function(f) => {
                declarations.push(
                    declare::uuid_variable(id::function_uuid(&export.name), export_id).into(),
                );

                let mut function_declarations: Vec<Declaration> = Vec::new();

                function_declarations.push(declare::arora_buffer_reader("arg").into());

                function_declarations.push(
                    declare::assert(
                        declare::arora_buffer_reader_next_type()
                            .equal(constant::ARORA_BUFFER_TYPE_STRUCTURE.clone()),
                    )
                    .into(),
                );

                function_declarations.push(
                    Variable {
                        name: "structure_metadata".to_string(),
                        ty: ty::ARORA_GET_STRUCTURE_RESULT.clone(),
                        value: Some(declare::arora_buffer_reader_get_structure()),
                        ..Default::default()
                    }
                    .into(),
                );

                for parameter_id in f.parameter_ordering.iter() {
                    let parameter = f.parameters.get(parameter_id).unwrap();
                    function_declarations.push(
                        Variable {
                            name: parameter_variable_name(parameter_id, parameter),
                            ty: optional(
                                TypeRef {
                                    ty: ty::type_name(context, &parameter.ty).to_string(),
                                    ..Default::default()
                                },
                                true,
                                false,
                            ),
                            ..Default::default()
                        }
                        .into(),
                    );
                }

                let mut read_declarations: Vec<Declaration> = Vec::new();

                read_declarations.push(
                    Variable {
                        name: "field_index".to_string(),
                        ty: ty::U32.clone(),
                        value: Some("0".to_expression()),
                        ..Default::default()
                    }
                    .into(),
                );

                read_declarations.push(
                    Variable {
                        name: "field".to_string(),
                        ty: ty::U8_CONST_PTR.clone(),
                        value: Some(declare::arora_buffer_reader_get_structure_field()),
                        ..Default::default()
                    }
                    .into(),
                );

                read_declarations.push(
                    Variable {
                        name: "current_res".to_string(),
                        ty: ty::U8.clone(),
                        value: Some(0u64.to_expression()),
                        ..Default::default()
                    }
                    .into(),
                );

                let field = "field".to_expression();
                let field_index = "field_index".to_expression();
                let structure_metadata = "structure_metadata".to_expression();
                let field_count = "field_count".to_expression();
                let current_res = "current_res".to_expression();

                for (i, parameter_id) in f.parameter_ordering.iter().enumerate() {
                    let parameter = f.parameters.get(parameter_id).unwrap();
                    let mut field_declarations: Vec<Declaration> = Vec::new();

                    let name = parameter_variable_name(parameter_id, parameter).to_expression();
                    let type_name = ty::type_name(context, &parameter.ty);

                    field_declarations.push(
                        name.assign(declare::deserialize(&type_name))
                            .into_statement()
                            .into(),
                    );

                    field_declarations
                        .push(field_index.clone().pre_increment().into_statement().into());

                    if i < f.parameter_ordering.len() - 1 {
                        field_declarations.push(
                            field
                                .clone()
                                .assign(declare::arora_buffer_reader_get_structure_field())
                                .into_statement()
                                .into(),
                        );
                    }

                    read_declarations.push(
                        Statement::While(
                            field_index
                                .less_than(structure_metadata.dot(field_count.clone()))
                                .logical_and(
                                    current_res
                                        .assign(
                                            func::ARORA_UUID_COMPARE.call([
                                                field.clone(),
                                                id::parameter_uuid(&export.name, &parameter.name)
                                                    .to_expression(),
                                            ]),
                                        )
                                        .parenthesized(),
                                )
                                .less_than("0".to_expression()),
                            Block {
                                statements: vec![
                                    field_index.clone().pre_increment().into_statement().into(),
                                    field
                                        .clone()
                                        .assign(declare::arora_buffer_reader_get_structure_field())
                                        .into_statement()
                                        .into(),
                                ],
                                semicolon: false,
                            },
                        )
                        .into(),
                    );

                    read_declarations.push(
                        Statement::If(
                            field_index
                                .less_than(structure_metadata.dot(field_count.clone()))
                                .logical_and(current_res.equal("0".to_expression())),
                            Block {
                                statements: field_declarations,
                                ..Default::default()
                            },
                            None,
                        )
                        .into(),
                    );
                }

                function_declarations.push(
                    Statement::If(
                        structure_metadata
                            .dot(field_count.clone())
                            .greater_than("0".to_expression())
                            .logical_and(
                                func::ARORA_UUID_COMPARE
                                    .call([
                                        Expression::Dot(
                                            "structure_metadata".to_expression().into(),
                                            "id".to_expression().into(),
                                        ),
                                        id::function_uuid(&export.name).to_expression(),
                                    ])
                                    .equal("0".to_expression()),
                            ),
                        Block {
                            statements: read_declarations,
                            ..Default::default()
                        },
                        None,
                    )
                    .into(),
                );

                function_declarations.push(
                    func::ARORA_BUFFER_READER_FREE
                        .call(["reader"])
                        .into_statement()
                        .into(),
                );

                function_declarations.push(
                    Variable {
                        name: "result".to_string(),
                        ty: TypeRef {
                            ty: ty::type_name(context, &f.return_ty).to_string(),
                            ..Default::default()
                        },
                        value: Some(
                            identifier_name(&module.name)
                                .to_expression()
                                .colon_colon(export.name.to_expression())
                                .call(f.parameter_ordering.iter().map(|parameter_id| {
                                    let parameter = f.parameters.get(parameter_id).unwrap();
                                    parameter_variable_name(parameter_id, parameter)
                                })),
                        ),
                        ..Default::default()
                    }
                    .into(),
                );

                function_declarations.push(declare::arora_buffer_writer().into());

                let mutable_parameters = f.parameter_ordering.iter().filter_map(|parameter_id| {
                    let parameter = f.parameters.get(parameter_id).unwrap();
                    if parameter.mutable {
                        Some((parameter_id, parameter))
                    } else {
                        None
                    }
                });
                let field_count = mutable_parameters.clone().count() as u32 + 1;

                // Return is always written first by convention
                function_declarations.push(
                    declare::arora_buffer_writer_begin_structure(
                        &id::function_uuid(&export.name),
                        field_count.to_expression(),
                    )
                    .into(),
                );

                // Return value is written under the method's UUID
                function_declarations.push(
                    declare::arora_buffer_writer_add_structure_field(
                        id::function_uuid(&export.name).to_expression(),
                    )
                    .into(),
                );

                function_declarations.push(
                    declare::serialize(
                        &ty::type_name(context, &f.return_ty),
                        &"result".to_expression(),
                    )
                    .into(),
                );

                for (_, parameter) in mutable_parameters {
                    function_declarations.push(
                        declare::arora_buffer_writer_add_structure_field(
                            id::parameter_uuid(&export.name, &parameter.name).to_expression(),
                        )
                        .into(),
                    );

                    function_declarations.push(
                        declare::serialize(
                            &ty::type_name(context, &parameter.ty),
                            &parameter.name.to_expression(),
                        )
                        .into(),
                    );
                }

                function_declarations.push(
                    Variable {
                        name: "result_buffer".to_string(),
                        ty: ty::U8_CONST_PTR.clone(),
                        value: Some(declare::arora_buffer_writer_finalize()),
                        ..Default::default()
                    }
                    .into(),
                );

                // Free the writer
                function_declarations.push(declare::arora_buffer_writer_free().into());

                function_declarations.push(
                    "return result_buffer"
                        .to_expression()
                        .into_statement()
                        .into(),
                );

                for parameter_id in f.parameter_ordering.iter() {
                    let parameter = f.parameters.get(parameter_id).unwrap();
                    declarations.push(
                        declare::uuid_variable(
                            id::parameter_uuid(&export.name, &parameter.name),
                            parameter_id,
                        )
                        .into(),
                    );
                }

                let function_name = format!("arora_function_{}", identifier_uuid(export_id));

                declarations.push(
                    Extern {
                        name: "C".to_string(),
                        block: Block {
                            statements: vec![FunctionImplementation {
                                attributes: Some(vec![format!(
                                    "export_name(\"{}\")",
                                    function_name
                                )]),
                                name: function_name,
                                ret: Some(ty::U8_CONST_PTR.clone()),
                                parameters: vec![ast::Parameter {
                                    name: "arg".to_string(),
                                    type_ref: ty::U8_CONST_PTR.clone(),
                                }],
                                body: Block {
                                    statements: function_declarations,
                                    ..Default::default()
                                },
                                ..Default::default()
                            }
                            .into()],
                            ..Default::default()
                        },
                    }
                    .into(),
                );
            }
        }
    }

    Ok(TranslationUnit { declarations })
}

fn generate_self<'a>(context: &Context<'a>) -> anyhow::Result<Directory> {
    let module = context.module.as_ref().unwrap();

    let mut source = Directory::new();

    source.insert(
        format!("{}.cpp", module.name),
        File::new(generate_self_source(context)?.to_pretty_string(0)),
    )?;

    let mut include = Directory::new();

    include.insert(
        format!("{}.hpp", module.name),
        File::new(generate_self_header(context)?.to_pretty_string(0)),
    )?;

    let mut root = Directory::new();
    root.insert("source", source)?;
    root.insert("include", include)?;

    // Write out a C++ header
    Ok(root)
}

/// Generates a directory describing the module in a layout compatible with `arora-module-cli --include`.
fn generate_self_record<'a>(context: &Context<'a>) -> anyhow::Result<Directory> {
    let module = context.module.as_ref().unwrap();
    let mut result = Directory::new();
    let modules_dir = result.ensure_directories(&PathBuf::from_str("records/module/")?)?;
    let module_path = format!("{}@{}.yaml", context.module_id, context.module_version);
    let module_yaml = serde_yaml::to_string(&module).unwrap();
    modules_dir.insert(module_path, File::new(module_yaml.as_bytes()))?;
    Ok(result)
}

#[tokio::main]
async fn main() -> anyhow::Result<()> {
    let args = Args::parse();
    let self_id = Uuid::parse_str(&args.self_id)?;
    let self_version = Version::parse(&args.self_version)?;

    let mut stdin = stdin();
    let mut stdout = stdout();
    let mut reader = Reader::new(&mut stdin);

    let mut assets = Vec::new();

    while let Ok(Some(asset)) = reader.read().await {
        assets.push(asset);
    }

    let mut context = Context {
        args: &args,
        types: HashMap::new(),
        grouped_import_symbols: HashMap::new(),
        module_id: self_id,
        module_version: self_version,
        module: None,
    };

    for asset in assets {
        match asset {
            ModuleAsset::Type(type_id, _, type_def) => {
                context.types.insert(type_id, type_def);
            }
            ModuleAsset::Import(import) => {
                match context
                    .grouped_import_symbols
                    .entry(import.module_id.to_owned())
                {
                    hash_map::Entry::Occupied(mut entry) => {
                        entry.get_mut().push(import);
                    }
                    hash_map::Entry::Vacant(entry) => {
                        entry.insert(vec![import]);
                    }
                }
            }
            ModuleAsset::Module(module_id, _, module, _) => {
                if module_id != context.module_id {
                    anyhow::bail!("Module ID differs from self ID");
                }
                context.module = Some(module);
            }
        }
    }

    let mut root = Directory::new();
    for id in context.types.keys() {
        root = root.merge_with(&generate_type(&context, id)?);
    }
    for imports in context.grouped_import_symbols.values() {
        root = root.merge_with(&generate_module_imports(&context, imports)?);
    }
    root = root.merge_with(&generate_self(&context)?);
    root = root.merge_with(&generate_self_record(&context)?);

    let mut writer = Writer::new(&mut stdout);

    writer
        .write::<arora_vfs::Entry>(Entry::Directory(root))
        .await?;
    writer.end().await?;
    stdout.flush().await?;

    Ok(())
}
