use std::{path::Path, str::FromStr, sync::Arc, collections::HashMap};
use arora_vfs::{Entry, Directory, File};
use ast::{TranslationUnit, PreprocessorDirective, Namespace, Declaration, FunctionPrototype, TypeRef, Parameter, NewLine, IncludeStyle, FunctionImplementation, Block, Expression, Statement, ArrayKind, Extern};
use clap::Parser;

use arora_module_core::{Reader, Asset, Writer};

use arora_schema::{
  ty::{low::{Type}, PRIMITIVE_IDS, UNIT_ID, BOOLEAN_ID, U8_ID, U16_ID, U32_ID, U64_ID, S8_ID, S16_ID, S32_ID, S64_ID, R32_ID, R64_ID, STRING_ID, ARRAY_ID},
  module::low::{ImportSymbol, ExportSymbol, Header, Parameter as LowParameter}
};
use tokio::io::{stdin, stdout, AsyncWriteExt};
use convert_case::{Case, Casing};
use uuid::Uuid;

pub mod ast;
use ast::{ToPrettyString, ToExpression};

pub mod ty;
pub mod func;
pub mod constant;
pub mod id;
pub mod declare;

use crate::ast::Variable;

pub const AUTOGENERATED_WARNING: &str = "// This file was autogenerated by arora-module-cli. Do not edit.\n";

#[derive(Debug)]
pub enum NameStyle {
  UpperCamelCase,
  LowerCamelCase,
  SnakeCase,
}

impl NameStyle {
  pub fn convert(&self, name: &str) -> String {
    let name = name.replace('_', " ");
    match self {
      Self::UpperCamelCase => name.to_case(Case::UpperCamel),
      Self::LowerCamelCase => name.to_case(Case::Camel),
      Self::SnakeCase => name.to_case(Case::Snake),
    }
  }
}

impl FromStr for NameStyle {
  type Err = anyhow::Error;

  fn from_str(s: &str) -> Result<Self, Self::Err> {
    match s {
      "upper_camel" => Ok(Self::UpperCamelCase),
      "camel" => Ok(Self::LowerCamelCase),
      "snake" => Ok(Self::SnakeCase),
      _ => Err(anyhow::anyhow!("Invalid method name style: {}", s)),
    }
  }
}

#[derive(Parser, Debug)]
#[clap(long_about = None)]
pub struct Args {
  #[clap(short, long, name = "self-id")]
  pub self_id: String,

  #[clap(short, long, name = "method-style", default_value = "camel")]
  pub method_style: NameStyle,

  #[clap(short, long, name = "variable-style", default_value = "snake")]
  pub variable_style: NameStyle,

  #[clap(short, long, name = "type-style", default_value = "upper_camel")]
  pub type_style: NameStyle,
  
  #[clap(short, long, name = "namespace-style", default_value = "snake")]
  pub namespace_style: NameStyle,
}

pub struct Context<'a> {
  pub args: &'a Args,
  pub types: HashMap<Uuid, Type>,
  pub grouped_import_symbols: HashMap<Uuid, Vec<ImportSymbol>>,
  pub exports: HashMap<Uuid, ExportSymbol>,
  pub headers: HashMap<Uuid, Header>,
}

async fn generate_type<'a>(context: &Context<'a>, id: &Uuid) -> anyhow::Result<Arc<Directory>> {
  let ty = context.types.get(&id)
    .ok_or_else(|| anyhow::anyhow!("Type not found: {}", id))?;

  let mut source = Directory::new();
  let mut source_types = Directory::new();

  let mut source_content = new_cpp_file();

  source_types.insert(format!("{}.cpp", ty.name), File::new(source_content));

  source.insert("types", source_types);

  let mut include = Directory::new();
  let mut include_types = Directory::new();

  let mut include_content = new_cpp_file();

  include_types.insert(format!("{}.hpp", ty.name), File::new(include_content));

  include.insert("types", include_types);

  let mut root = Directory::new();
  root.insert("source", source);
  root.insert("include", include);

  // Write out a C++ header 
  Ok(root.into())
}



async fn generate_module<'a>(context: &Context<'a>, id: &Uuid) -> anyhow::Result<Arc<Directory>> {
  let header = context.headers.get(&id)
    .ok_or_else(|| anyhow::anyhow!("Module {} not found", id))?;
  let imports = context.grouped_import_symbols.get(&id)
    .ok_or_else(|| anyhow::anyhow!("Module {} not found", id))?;

  let mut source = Directory::new();

  let mut source_content = new_cpp_file();


  source.insert(format!("{}.cpp", header.name), File::new(source_content));

  let mut include = Directory::new();

  let mut include_content = new_cpp_file();

  include.insert(format!("{}.hpp", header.name), File::new(include_content));

  let mut root = Directory::new();
  root.insert("source", source);
  root.insert("include", include);

  // Write out a C++ header 
  Ok(root.into())
}

fn new_cpp_file() -> String {
  let mut source_content = String::new();
  source_content.push_str(AUTOGENERATED_WARNING);
  source_content.push_str("\n");
  source_content
}

fn include_guard_name(name: &str) -> String {
  format!("_{}_HPP_", name
    .replace('-', "_")
    .to_uppercase())
}

fn identifier_name(name: &str) -> String {
  name.replace('-', "_")
}

fn identifier_uuid(uuid: &Uuid) -> String {
  uuid.to_string().replace("-", "_")
}

fn include_guard_begin(name: &str) -> String {
  let mut ret = String::new();
  
  let name = include_guard_name(name);
  
  ret.push_str("#ifndef ");
  ret.push_str(&name);
  ret.push_str("\n");
  ret.push_str("#define ");
  ret.push_str(&name);
  ret.push_str("\n");

  ret
}

fn include_guard_end(name: &str) -> String {
  let name = include_guard_name(name);

  let mut ret = String::new();
  ret.push_str("\n");
  ret.push_str("#endif // ");
  ret.push_str(&name);
  ret
}



fn optional(type_ref: TypeRef, mutable: bool, reference: bool) -> TypeRef {
  TypeRef {
    ty: "std::optional".to_string(),
    arguments: Some(vec! [
      type_ref
    ]),
    constant: !mutable,
    reference,
    ..Default::default()
  }
}

fn generate_self_header<'a>(context: &Context<'a>, id: &Uuid) -> anyhow::Result<TranslationUnit> {
  let header = context.headers.get(&id).unwrap();

  let guard_name = include_guard_name(&header.name);
  let id_name = identifier_name(&header.name);

  let mut declarations = Vec::new();
  declarations.push(PreprocessorDirective::Ifndef(guard_name.clone()).into());
  declarations.push(PreprocessorDirective::Define(guard_name).into());
  declarations.push(NewLine { count: 1 }.into());

  declarations.push(PreprocessorDirective::Include("cstdint".to_string(), IncludeStyle::System).into());
  declarations.push(PreprocessorDirective::Include("optional".to_string(), IncludeStyle::System).into());


  for export in context.exports.values() {
    export.type_dependencies().iter().for_each(|dep| {
      if PRIMITIVE_IDS.contains(dep) {
        return;
      }
      
      let dep_header = context.types.get(dep).unwrap();
      declarations.push(PreprocessorDirective::Include(format!("types/{}.hpp", dep_header.name), IncludeStyle::Local).into());
    });
  }

  declarations.push(NewLine { count: 1 }.into());

  let mut namespace_declarations: Vec<Declaration> = Vec::new();

  for export in context.exports.values() {
    let name = export.name().clone();
    let name = context.args.method_style.convert(&name);
    match export {
      ExportSymbol::Function(f) => {
        let mut parameters = Vec::new();
        for parameter in f.parameters.iter() {
          parameters.push(Parameter {
            name: parameter.name.clone(),
            type_ref: optional(TypeRef {
              ty: ty::type_name(context, &parameter.ty).to_string(),
              ..Default::default()
            }, parameter.mutable, true),
          });
        }

        namespace_declarations.push(FunctionPrototype {
          name: name,
          ret: TypeRef {
            ty: ty::type_name(context, &f.ret).to_string(),
            ..Default::default()
          },
          parameters,
        }.into());
      },
    }
    
  }

  declarations.push(Namespace {
    name: id_name.clone(),
    declarations: namespace_declarations,
  }.into());

  declarations.push(NewLine { count: 1 }.into());
  declarations.push(PreprocessorDirective::Endif.into());

  Ok(TranslationUnit {
    declarations
  })
}



fn generate_self_source<'a>(context: &Context<'a>, id: &Uuid) -> anyhow::Result<TranslationUnit> {
  let header = context.headers.get(&id).unwrap();


  let mut declarations = Vec::new();
  declarations.push(PreprocessorDirective::Include(format!("{}.hpp", &header.name), IncludeStyle::Local).into());
  declarations.push(PreprocessorDirective::Include(format!("cassert"), IncludeStyle::System).into());
  declarations.push(Extern {
    name: "C".to_string(),
    block: Block {
      statements: vec! [
        PreprocessorDirective::Include(format!("arora/buffers.h"), IncludeStyle::System).into(),
        PreprocessorDirective::Include(format!("arora/util.h"), IncludeStyle::System).into()
      ],
      ..Default::default()
    }
  }.into());
  declarations.push(PreprocessorDirective::Include(format!("arora/buffer/deserialize.hpp"), IncludeStyle::System).into());
  declarations.push(PreprocessorDirective::Include(format!("arora/buffer/serialize.hpp"), IncludeStyle::System).into());

  declarations.push(NewLine { count: 1 }.into());

  declarations.push(declare::uuid_variable(id::module_uuid(&header.name), &header.id).into());

  for export in context.exports.values() {
    let name = export.name().clone();
    let name = context.args.method_style.convert(&name);

    match export {
      ExportSymbol::Function(f) => {
        let mut sorted_parameters: Vec<&LowParameter> = f.parameters.iter().collect();
        sorted_parameters.sort_by(|a, b| a.id.cmp(&b.id));

        declarations.push(declare::uuid_variable(id::function_uuid(&f.name), &f.id).into());

        let mut function_declarations: Vec<Declaration> = Vec::new();

        function_declarations.push(declare::arora_buffer_reader("arg").into());

        function_declarations.push(
          declare::assert(
            declare::arora_buffer_reader_next_type().equal(constant::ARORA_BUFFER_TYPE_STRUCTURE.clone())
          ).into()
        );

        function_declarations.push(Variable {
          name: "structure_metadata".to_string(),
          ty: ty::ARORA_GET_STRUCTURE_RESULT.clone(),
          value: Some(declare::arora_buffer_reader_get_structure()),
          ..Default::default()
        }.into());

        for parameter in sorted_parameters.iter() {
          function_declarations.push(Variable {
            name: parameter.name.clone(),
            ty: optional(TypeRef {
              ty: ty::type_name(context, &parameter.ty).to_string(),
              ..Default::default()
            }, true, false),
            ..Default::default()
          }.into());
        }

        let mut read_declarations: Vec<Declaration> = Vec::new();

        read_declarations.push(Variable {
          name: "field_index".to_string(),
          ty: ty::U32.clone(),
          value: Some("0".to_expression()),
          ..Default::default()
        }.into());


        read_declarations.push(Variable {
          name: "field".to_string(),
          ty: ty::U8_CONST_PTR.clone(),
          value: Some(declare::arora_buffer_reader_get_structure_field()),
          ..Default::default()
        }.into());

        let field = "field".to_expression();
        let field_index = "field_index".to_expression();
        let structure_metadata = "structure_metadata".to_expression();
        let field_count = "field_count".to_expression();


        let mut i = 0;
        for parameter in sorted_parameters.iter() {

          let mut field_declarations: Vec<Declaration> = Vec::new();

          let name = parameter.name.to_expression();
          let type_name = ty::type_name(context, &parameter.ty);

          field_declarations.push(
            name.assign(declare::deserialize(&parameter.name, &type_name)).into_statement().into()
          );

          field_declarations.push(field_index.clone().pre_increment().into_statement().into());
          
          if i < sorted_parameters.len() - 1 {
            field_declarations.push(field.clone().assign(declare::arora_buffer_reader_get_structure_field()).into_statement().into());
          }
          
          read_declarations.push(Statement::If(
            field_index.clone().less_than(structure_metadata.dot(field_count.clone())).logical_and(
            func::ARORA_UUID_COMPARE.call([
              field.clone(),
              id::parameter_uuid(&export.name(), &parameter.name).to_expression()
            ]).equal("0".to_expression())),
            Block {
              statements: field_declarations,
              ..Default::default()
            },
            None
          ).into());

          i += 1;
        }
        
        
        function_declarations.push(
          Statement::If(
            structure_metadata.dot(field_count.clone()).greater_than("0".to_expression()).logical_and(
            func::ARORA_UUID_COMPARE.call([
              Expression::Dot("structure_metadata".to_expression().into(), "id".to_expression().into()),
              id::function_uuid(&f.name).to_expression()
            ]).equal("0".to_expression())).into(),
            Block {
              statements: read_declarations,
              ..Default::default()
            },
            None
          ).into()
        );

        function_declarations.push(func::ARORA_BUFFER_READER_FREE.call([ "reader" ]).into_statement().into());

        function_declarations.push(Variable {
          name: "__arora_return__".to_string(),
          ty: TypeRef {
            ty: ty::type_name(context, &f.ret).to_string(),
            ..Default::default()
          },
          value: Some(identifier_name(&header.name).to_expression().colon_colon(f.name.to_expression())
              .call(f.parameters.iter().map(|p| p.name.to_expression()))),
          ..Default::default()
        }.into());

        function_declarations.push(declare::arora_buffer_writer().into());

        let mut field_count = 1;
        for parameter in sorted_parameters.iter() {
          if !parameter.mutable {
            continue;
          }

          field_count += 1;
        }
        
        // Return is always written first by convention
        function_declarations.push(declare::arora_buffer_writer_begin_structure(&id::function_uuid(&f.name), field_count).into());

        // Return value is written under the method's UUID
        function_declarations.push(declare::arora_buffer_writer_add_structure_field(&id::function_uuid(&f.name)).into());

        function_declarations.push(declare::serialize(&ty::type_name(context, &f.ret), &"__arora_return__".to_expression()).into());

        for parameter in sorted_parameters.iter() {
          if !parameter.mutable {
            continue;
          }

          function_declarations.push(declare::arora_buffer_writer_add_structure_field(&id::parameter_uuid(&export.name(), &parameter.name)).into());

          function_declarations.push(declare::serialize(&ty::type_name(context, &parameter.ty), &parameter.name.to_expression()).into());
        }

        // Free the writer
        function_declarations.push(declare::arora_buffer_writer_free().into());

        function_declarations.push("return arora_buffer_writer_finalize(writer, 0)".to_expression().into_statement().into());

        for parameter in sorted_parameters.iter() {
          declarations.push(declare::uuid_variable(id::parameter_uuid(&export.name(), &parameter.name), &parameter.id).into());
        }

        let function_name = format!("arora_function_{}", identifier_uuid(&f.id));

        declarations.push(Extern {
          name: "C".to_string(),
          block: Block {
            statements: vec![
              FunctionImplementation {
                attributes: Some(vec![
                  format!("export_name(\"{}\")", function_name).into(),
                ]),
                name: function_name,
                ret: ty::U8_CONST_PTR.clone(),
              parameters: vec! [
                Parameter {
                  name: "arg".to_string(),
                  type_ref: ty::U8_CONST_PTR.clone(),
                }
              ],
              body: Block {
                statements: function_declarations,
                ..Default::default()
              },
            }.into(),
            ],
            ..Default::default()
          }
        }.into());
      },
    }
  }

  Ok(TranslationUnit {
    declarations
  })
}


async fn generate_self<'a>(context: &Context<'a>, id: &Uuid) -> anyhow::Result<Arc<Directory>> {
  let header = context.headers.get(&id).unwrap();

  let mut source = Directory::new();

  source.insert(
    format!("{}.cpp", header.name),
    File::new(generate_self_source(context, id)?.to_pretty_string(0))
  );

  let mut include = Directory::new();

  // namespace
  

  include.insert(
    format!("{}.hpp", header.name), 
    File::new(generate_self_header(context, id)?.to_pretty_string(0))
  );

  let mut root = Directory::new();
  root.insert("source", source);
  root.insert("include", include);

  // Write out a C++ header 
  Ok(root.into())
}

#[tokio::main]
async fn main() -> anyhow::Result<()> {
  let args = Args::parse();
  let self_id = Uuid::parse_str(&args.self_id)?;

  let mut stdin = stdin();
  let mut stdout = stdout();
  let mut reader = Reader::new(&mut stdin);
  
  
  let mut assets = Vec::new();

  while let Ok(Some(asset)) = reader.read().await {
    assets.push(asset);
  }

  let mut context = Context {
    args: &args,
    types: HashMap::new(),
    grouped_import_symbols: HashMap::new(),
    exports: HashMap::new(),
    headers: HashMap::new(),
  };

  for asset in assets {
    match asset {
      Asset::Type(ty) => {
        context.types.insert(ty.id, ty);
      }, 
      Asset::ImportSymbol(symbol) => {
        if let Some(existing) = context.grouped_import_symbols.get_mut(symbol.module()) {
          existing.push(symbol);
        } else {
          context.grouped_import_symbols.insert(symbol.module().clone(), vec![symbol]);
        }
      },
      Asset::ExportSymbol(symbol) => {
        context.exports.insert(symbol.id().clone(), symbol);
      },
      Asset::Header(header) => {
        context.headers.insert(header.id, header);
      }
    }
  }

  let mut root = Arc::new(Directory::new());
  for id in context.types.keys() {
    root = root.merge_with( generate_type(&context, id).await?);
  }

  for id in context.headers.keys() {
    if id == &self_id {
      root = root.merge_with(generate_self(&context, &self_id).await?);
    } else {
      root = root.merge_with(generate_module(&&context, id).await?);
    }
  }

  let mut writer = Writer::new(&mut stdout);

  writer.write::<arora_vfs::Entry>(Entry::Directory(root)).await?;
  writer.end().await?;
  stdout.flush().await?;

  Ok(())
}
