name: Build and Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:

    - name: Setup Rust Target Platform
      run: |
        rustup target add wasm32-unknown-unknown
        rustup target add wasm32-wasi

    - name: Install Rust WASI
      run: cargo install cargo-wasi

    - name: Install Wasmtime
      run: |
        curl https://wasmtime.dev/install.sh -sSf | bash
        source ~/.bashrc

    - uses: actions/checkout@v2

    - name: Configure
      run: ${{github.workspace}}/configure.py

    - name: Build
      run: cmake --build ${{github.workspace}}/build
      env:
        RUST_BACKTRACE: 1

    - name: Test
      working-directory: ${{github.workspace}}/build
      # Execute tests defined by the CMake configuration.  
      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
      run: ctest -V -C ${{env.BUILD_TYPE}}
      env:
        RUST_BACKTRACE: 1

